// nextjs layout

import React from "react";
import { Inter } from "next/font/google";

import "../globals.css";
import { AuthProvider } from "@/components/providers/AuthProvider";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={`${inter.className}`}>{children}</body>
        <Toaster />
      </html>
    </AuthProvider>
  );
}
