// import { Inter } from "next/font/google";
import "./globals.css";
// import { Providers } from "@/components/providers/themeProviders";
// import Topbar from "@/components/Share/TopBar";
// import SideBar from "@/components/Share/Sidebar";
// import { Toaster } from "@/components/ui/sonner";
// import { AuthProvider } from "@/components/providers/AuthProvider";

import SideBar from "@/components/Share/Sidebar";
import Topbar from "@/components/Share/TopBar";
import { Providers } from "@/components/providers/themeProviders";
import { Toaster } from "@/components/ui/sonner";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <Topbar />
          <main className="flex flex-row">
            <SideBar />
            <section className=" w-full">
              <div className="container bg-muted/40">{children}</div>
            </section>
          </main>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
